name: CI
on: [push]

jobs:
  select-xcode-with-fastlane-xcversion:
    runs-on: macos-11
    steps:
      - name: Sets xcode version with fastlane xcversion
        run: bundle exec fastlane ios xcversion_test
  select-xcode-with-fastlane-xcode-select:
    runs-on: macos-11
    steps:
      - name: Sets xcode version with fastlane xcode-select
        run: bundle exec fastlane ios xcode_select_test
